# Generated by Django 3.0.8 on 2020-07-05 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_poll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='option_one_count',
            new_name='sum_total',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_three_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_two_count',
        ),
    ]
