# Generated by Django 3.0.8 on 2020-07-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200705_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='sum_total',
        ),
    ]
